// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqKSil4S51v8SdhtO39pc2qAzQh7hoyK8',
    appId: '1:816218581647:web:48b5d64caadb194d181efa',
    messagingSenderId: '816218581647',
    projectId: 'kagyokanri',
    authDomain: 'kagyokanri.firebaseapp.com',
    storageBucket: 'kagyokanri.appspot.com',
    measurementId: 'G-CK6PD4YN0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZMejltyUvZat1v0dwIXmG87aiP1JD2hA',
    appId: '1:816218581647:android:0d0004830af5e249181efa',
    messagingSenderId: '816218581647',
    projectId: 'kagyokanri',
    storageBucket: 'kagyokanri.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhOW3rY3cEO0ntViql8SVbE-PpCBh09jc',
    appId: '1:816218581647:ios:79a51289d353d44a181efa',
    messagingSenderId: '816218581647',
    projectId: 'kagyokanri',
    storageBucket: 'kagyokanri.appspot.com',
    iosBundleId: 'com.YogaSchoolKailas.kagyo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhOW3rY3cEO0ntViql8SVbE-PpCBh09jc',
    appId: '1:816218581647:ios:515e00b8a7d9d116181efa',
    messagingSenderId: '816218581647',
    projectId: 'kagyokanri',
    storageBucket: 'kagyokanri.appspot.com',
    iosBundleId: 'com.YogaSchoolKailas.kagyo.RunnerTests',
  );
}
